export const dealsData = [
  {
    id: 1,
    pair: 'NEAR/USDT',
    type: 'SPOT',
    time: '1 мин. назад',
    profit: 58.6206,
    target: 4,
    date: '06.10.2022',
  },
  {
    id: 2,
    pair: 'BTC/USDT',
    type: 'FUTURES',
    time: '3 мин. назад',
    profit: 12.4,
    target: 2,
    date: '06.10.2022',
  },
  {
    id: 3,
    pair: 'SOL/USDT',
    type: 'SPOT',
    time: '10 мин. назад',
    profit: 24.2,
    target: 3,
    date: '05.10.2022',
  },
  {
    id: 4,
    pair: 'ETH/USDT',
    type: 'SPOT',
    time: '1 час назад',
    profit: 9.1,
    target: 1,
    date: '04.10.2022',
  },
  {
    id: 5,
    pair: 'XRP/USDT',
    type: 'FUTURES',
    time: '2 часа назад',
    profit: 31.5,
    target: 5,
    date: '03.10.2022',
  },
];
